# @format

version: '3.7'

services:
  front-end:
    container_name: front-end-dev
    build:
      context: front-end-dev
      dockerfile: Dockerfile-dev
      args:
        REACT_APP_API_BASE_URL: http://127.0.0.1:8080
    ports:
      - '80:3000'
    restart: always
    # depends_on: back-end
    networks:
      - frontend
    volumes:
      - ./front-end-dev/react/public:/usr/src/app/public
      - ./front-end-dev/react/src:/usr/src/app/src
    command: npm start

  back-end:
    container_name: back-end-dev
    build:
      context: back-end-dev
      dockerfile: Dockerfile-dev
    restart: always
    depends_on:
      - db-dev # This service depends on mysql. Start that first.
    environment: # Pass environment variables to the service
      SPRING_DATASOURCE_URL: jdbc:mysql://db-dev:3306/minimal_db?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: minimal
      SPRING_DATASOURCE_PASSWORD: minimal
    ports:
      - '8080:8080'
    volumes:
      - ./back-end-dev/app:/app
    working_dir: /app
    command: ./gradlew --project-cache-dir /tmp/gradle-cache bootRun
    networks:
      - backend
      - frontend

  db-dev:
    container_name: db-mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: minimal_db
      MYSQL_USER: minimal
      MYSQL_PASSWORD: minimal
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    ports:
      - 3306:3306
    volumes:
      - ./db-data-dev:/var/lib/mysql
    networks:
      - backend

volumes:
  db-data:

networks:
  backend:
  frontend:
